<?php

/**
 * Modello D – Rendiconto economico per cassa (GU 18-04-2020).
 * Voci fisse, nessuna tabella DB. Usate in prima nota e nel rendiconto.
 */
return [
    'schema' => 'MOD_D_RENDICONTO_PER_CASSA',
    'source' => 'Gazzetta Ufficiale 18-04-2020',
    'accounts' => [
        [
            'code' => 'EXP_A',
            'type' => 'macro_area',
            'section' => 'EXPENSES',
            'area' => 'A',
            'name' => 'Uscite da attività di interesse generale',
            'children' => [
                ['code' => 'EXP_A_1', 'type' => 'expense', 'name' => 'Materie prime, sussidiarie, di consumo e di merci', 'ministerial_code' => 'A.1'],
                ['code' => 'EXP_A_2', 'type' => 'expense', 'name' => 'Servizi', 'ministerial_code' => 'A.2'],
                ['code' => 'EXP_A_3', 'type' => 'expense', 'name' => 'Godimento beni di terzi', 'ministerial_code' => 'A.3'],
                ['code' => 'EXP_A_4', 'type' => 'expense', 'name' => 'Personale', 'ministerial_code' => 'A.4'],
                ['code' => 'EXP_A_5', 'type' => 'expense', 'name' => 'Uscite diverse di gestione', 'ministerial_code' => 'A.5'],
            ],
        ],
        [
            'code' => 'INC_A',
            'type' => 'macro_area',
            'section' => 'INCOME',
            'area' => 'A',
            'name' => 'Entrate da attività di interesse generale',
            'children' => [
                ['code' => 'INC_A_1', 'type' => 'income', 'name' => 'Entrate da quote associative e apporti dei fondatori', 'ministerial_code' => 'A.1'],
                ['code' => 'INC_A_2', 'type' => 'income', 'name' => 'Entrate dagli associati per attività mutuali', 'ministerial_code' => 'A.2'],
                ['code' => 'INC_A_3', 'type' => 'income', 'name' => 'Entrate per prestazioni e cessioni ad associati e fondatori', 'ministerial_code' => 'A.3'],
                ['code' => 'INC_A_4', 'type' => 'income', 'name' => 'Erogazioni liberali', 'ministerial_code' => 'A.4'],
                ['code' => 'INC_A_5', 'type' => 'income', 'name' => 'Entrate del 5 per mille', 'ministerial_code' => 'A.5'],
                ['code' => 'INC_A_6', 'type' => 'income', 'name' => 'Contributi da soggetti privati', 'ministerial_code' => 'A.6'],
                ['code' => 'INC_A_7', 'type' => 'income', 'name' => 'Entrate per prestazioni e cessioni a terzi', 'ministerial_code' => 'A.7'],
                ['code' => 'INC_A_8', 'type' => 'income', 'name' => 'Contributi da enti pubblici', 'ministerial_code' => 'A.8'],
                ['code' => 'INC_A_9', 'type' => 'income', 'name' => 'Entrate da contratti con enti pubblici', 'ministerial_code' => 'A.9'],
                ['code' => 'INC_A_10', 'type' => 'income', 'name' => 'Altre entrate', 'ministerial_code' => 'A.10'],
            ],
        ],
        [
            'code' => 'EXP_B',
            'type' => 'macro_area',
            'section' => 'EXPENSES',
            'area' => 'B',
            'name' => 'Uscite da attività diverse',
            'children' => [
                ['code' => 'EXP_B_1', 'type' => 'expense', 'name' => 'Materie prime, sussidiarie, di consumo e di merci', 'ministerial_code' => 'B.1'],
                ['code' => 'EXP_B_2', 'type' => 'expense', 'name' => 'Servizi', 'ministerial_code' => 'B.2'],
                ['code' => 'EXP_B_3', 'type' => 'expense', 'name' => 'Godimento beni di terzi', 'ministerial_code' => 'B.3'],
                ['code' => 'EXP_B_4', 'type' => 'expense', 'name' => 'Personale', 'ministerial_code' => 'B.4'],
                ['code' => 'EXP_B_5', 'type' => 'expense', 'name' => 'Uscite diverse di gestione', 'ministerial_code' => 'B.5'],
            ],
        ],
        [
            'code' => 'INC_B',
            'type' => 'macro_area',
            'section' => 'INCOME',
            'area' => 'B',
            'name' => 'Entrate da attività diverse',
            'children' => [
                ['code' => 'INC_B_1', 'type' => 'income', 'name' => 'Entrate per prestazioni e cessioni ad associati e fondatori', 'ministerial_code' => 'B.1'],
                ['code' => 'INC_B_2', 'type' => 'income', 'name' => 'Contributi da soggetti privati', 'ministerial_code' => 'B.2'],
                ['code' => 'INC_B_3', 'type' => 'income', 'name' => 'Entrate per prestazioni e cessioni a terzi', 'ministerial_code' => 'B.3'],
                ['code' => 'INC_B_4', 'type' => 'income', 'name' => 'Contributi da enti pubblici', 'ministerial_code' => 'B.4'],
                ['code' => 'INC_B_5', 'type' => 'income', 'name' => 'Entrate da contratti con enti pubblici', 'ministerial_code' => 'B.5'],
                ['code' => 'INC_B_6', 'type' => 'income', 'name' => 'Altre entrate', 'ministerial_code' => 'B.6'],
            ],
        ],
        [
            'code' => 'EXP_C',
            'type' => 'macro_area',
            'section' => 'EXPENSES',
            'area' => 'C',
            'name' => 'Uscite da attività di raccolta fondi',
            'children' => [
                ['code' => 'EXP_C_1', 'type' => 'expense', 'name' => 'Uscite per raccolte fondi abituali', 'ministerial_code' => 'C.1'],
                ['code' => 'EXP_C_2', 'type' => 'expense', 'name' => 'Uscite per raccolte fondi occasionali', 'ministerial_code' => 'C.2'],
                ['code' => 'EXP_C_3', 'type' => 'expense', 'name' => 'Altre uscite', 'ministerial_code' => 'C.3'],
            ],
        ],
        [
            'code' => 'INC_C',
            'type' => 'macro_area',
            'section' => 'INCOME',
            'area' => 'C',
            'name' => 'Entrate da attività di raccolta fondi',
            'children' => [
                ['code' => 'INC_C_1', 'type' => 'income', 'name' => 'Entrate da raccolte fondi abituali', 'ministerial_code' => 'C.1'],
                ['code' => 'INC_C_2', 'type' => 'income', 'name' => 'Entrate da raccolte fondi occasionali', 'ministerial_code' => 'C.2'],
                ['code' => 'INC_C_3', 'type' => 'income', 'name' => 'Altre entrate', 'ministerial_code' => 'C.3'],
            ],
        ],
        [
            'code' => 'EXP_D',
            'type' => 'macro_area',
            'section' => 'EXPENSES',
            'area' => 'D',
            'name' => 'Uscite da attività finanziarie e patrimoniali',
            'children' => [
                ['code' => 'EXP_D_1', 'type' => 'expense', 'name' => 'Su rapporti bancari', 'ministerial_code' => 'D.1'],
                ['code' => 'EXP_D_2', 'type' => 'expense', 'name' => 'Su investimenti finanziari', 'ministerial_code' => 'D.2'],
                ['code' => 'EXP_D_3', 'type' => 'expense', 'name' => 'Su patrimonio edilizio', 'ministerial_code' => 'D.3'],
                ['code' => 'EXP_D_4', 'type' => 'expense', 'name' => 'Su altri beni patrimoniali', 'ministerial_code' => 'D.4'],
                ['code' => 'EXP_D_5', 'type' => 'expense', 'name' => 'Altre uscite', 'ministerial_code' => 'D.5'],
            ],
        ],
        [
            'code' => 'INC_D',
            'type' => 'macro_area',
            'section' => 'INCOME',
            'area' => 'D',
            'name' => 'Entrate da attività finanziarie e patrimoniali',
            'children' => [
                ['code' => 'INC_D_1', 'type' => 'income', 'name' => 'Da rapporti bancari', 'ministerial_code' => 'D.1'],
                ['code' => 'INC_D_2', 'type' => 'income', 'name' => 'Da altri investimenti finanziari', 'ministerial_code' => 'D.2'],
                ['code' => 'INC_D_3', 'type' => 'income', 'name' => 'Da patrimonio edilizio', 'ministerial_code' => 'D.3'],
                ['code' => 'INC_D_4', 'type' => 'income', 'name' => 'Da altri beni patrimoniali', 'ministerial_code' => 'D.4'],
                ['code' => 'INC_D_5', 'type' => 'income', 'name' => 'Altre entrate', 'ministerial_code' => 'D.5'],
            ],
        ],
        [
            'code' => 'EXP_E',
            'type' => 'macro_area',
            'section' => 'EXPENSES',
            'area' => 'E',
            'name' => 'Uscite di supporto generale',
            'children' => [
                ['code' => 'EXP_E_1', 'type' => 'expense', 'name' => 'Materie prime, sussidiarie, di consumo e di merci', 'ministerial_code' => 'E.1'],
                ['code' => 'EXP_E_2', 'type' => 'expense', 'name' => 'Servizi', 'ministerial_code' => 'E.2'],
                ['code' => 'EXP_E_3', 'type' => 'expense', 'name' => 'Godimento beni di terzi', 'ministerial_code' => 'E.3'],
                ['code' => 'EXP_E_4', 'type' => 'expense', 'name' => 'Personale', 'ministerial_code' => 'E.4'],
                ['code' => 'EXP_E_5', 'type' => 'expense', 'name' => 'Altre uscite', 'ministerial_code' => 'E.5'],
            ],
        ],
        [
            'code' => 'INC_E',
            'type' => 'macro_area',
            'section' => 'INCOME',
            'area' => 'E',
            'name' => 'Entrate di supporto generale',
            'children' => [
                ['code' => 'INC_E_1', 'type' => 'income', 'name' => 'Entrate da distacco del personale', 'ministerial_code' => 'E.1'],
                ['code' => 'INC_E_2', 'type' => 'income', 'name' => 'Altre entrate di supporto generale', 'ministerial_code' => 'E.2'],
            ],
        ],
        [
            'code' => 'INVESTMENTS_AND_FINANCING',
            'type' => 'macro_area',
            'section' => 'OTHER',
            'area' => null,
            'name' => 'Entrate/Uscite per investimenti, disinvestimenti e finanziamenti',
            'children' => [
                ['code' => 'EXP_INV_1', 'type' => 'expense', 'name' => 'Investimenti in immobilizzazioni inerenti alle attività di interesse generale', 'ministerial_code' => 'INV.1'],
                ['code' => 'INC_DISINV_1', 'type' => 'income', 'name' => 'Disinvestimenti di immobilizzazioni inerenti alle attività di interesse generale', 'ministerial_code' => 'INV.2'],
                ['code' => 'EXP_INV_2', 'type' => 'expense', 'name' => 'Investimenti in immobilizzazioni inerenti alle attività diverse', 'ministerial_code' => 'INV.3'],
                ['code' => 'INC_DISINV_2', 'type' => 'income', 'name' => 'Disinvestimenti di immobilizzazioni inerenti alle attività diverse', 'ministerial_code' => 'INV.4'],
                ['code' => 'EXP_INV_3', 'type' => 'expense', 'name' => 'Investimenti in attività finanziarie e patrimoniali', 'ministerial_code' => 'INV.5'],
                ['code' => 'INC_DISINV_3', 'type' => 'income', 'name' => 'Disinvestimenti di attività finanziarie e patrimoniali', 'ministerial_code' => 'INV.6'],
                ['code' => 'EXP_FIN_1', 'type' => 'expense', 'name' => 'Rimborso di finanziamenti per quota capitale e di prestiti', 'ministerial_code' => 'INV.7'],
                ['code' => 'INC_FIN_1', 'type' => 'income', 'name' => 'Ricevimento di finanziamenti e di prestiti', 'ministerial_code' => 'INV.8'],
                ['code' => 'EXP_TAXES', 'type' => 'expense', 'name' => 'Imposte', 'ministerial_code' => 'INV.9'],
            ],
        ],
        [
            'code' => 'NOTIONAL_ITEMS',
            'type' => 'macro_area',
            'section' => 'OTHER',
            'area' => null,
            'name' => 'Costi e proventi figurativi (facoltativi)',
            'children' => [
                ['code' => 'EXP_NOTIONAL_A', 'type' => 'expense', 'name' => 'Costi figurativi da attività di interesse generale', 'ministerial_code' => 'NOT.1'],
                ['code' => 'EXP_NOTIONAL_B', 'type' => 'expense', 'name' => 'Costi figurativi da attività diverse', 'ministerial_code' => 'NOT.2'],
                ['code' => 'INC_NOTIONAL_A', 'type' => 'income', 'name' => 'Proventi figurativi da attività di interesse generale', 'ministerial_code' => 'NOT.3'],
                ['code' => 'INC_NOTIONAL_B', 'type' => 'income', 'name' => 'Proventi figurativi da attività diverse', 'ministerial_code' => 'NOT.4'],
            ],
        ],
    ],
];
